### ISSUE TITLE
Lista navi

### ISSUE THREAD

**Issue by giamberinigiulia** [LorenzoCorbinelli/BattagliaNavale#6]
Potrebbe essere sviluppato così: 
- nella fase di inserimento navi rimane la lista delle navi senza faccina;
- viene sostituita la lista con START non appena anche l'avversario ha terminato l'inserimento delle navi;
- successivamente alla prima mossa viene inserita la faccina?

La lista delle navi deve essere una label.

**Comment by ricca-meucci** [comment]
Fixed in 7d18c26b7
